autodraft/autodraft/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^d/', include('draftHost.urls', namespace="draftHost")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

autodraft/draftHost/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView
from draftHost import views, api

urlpatterns = patterns(
    'draftHost.views',
    url(r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.html',
                             content_type='text/plain')),
    url(r'^my_team/(?P<key>[^/]+)/?$', views.my_team, name='my_team'),
    url(r'^register/?$', views.register, name='register'),
    url(r'^mock_draft/?$', views.mock_draft, name='mock_draft'),
    url(r'^doc/$', views.documentation, name='documentation'),
    url(r'^draft/(?P<id>\d+)/?$', views.draft_detail, name='draft'),
    url(r'^draft/(?P<id>\d+)/picks/?$', views.draft_pick_ajax,
        name='pick_ajax'),
    url(r'^draft/(?P<id>\d+)/results/?$', views.draft_results, name="results"),
    url(r'^/?$', views.index, name='index'),
    url(r'^error/?$', views.reg_error, name='error'),

    # API v1
    url(r'^api/v1/', include(api, namespace="api"))
)

autodraft/draftHost/models.py
from django.db import models
from django.utils import timezone

class NflConference(models.Model):
    name = models.TextField()
    abbreviation = models.TextField(max_length=5)

    def __unicode__(self):
        return self.name


class NflDivision(models.Model):
    name = models.TextField()
    conference = models.ForeignKey(NflConference)

    def __unicode__(self):
        return self.name


class NflTeam(models.Model):
    """NFL Team"""
    name = models.TextField()
    abbreviation = models.TextField(max_length=5)
    city = models.TextField()
    division = models.ForeignKey(NflDivision)

    def __unicode__(self):
        return u"{a} - {c} {n}" \
            .format(c=self.city, n=self.name, a=self.abbreviation)


class NflPosition(models.Model):
    """Football position e.g. RB, QB, S"""
    description = models.TextField()
    abbreviation = models.TextField(max_length=4)

    def __unicode__(self):
        return self.description


class FantasyPosition(models.Model):
    """Fantasy position - a simple subset of NflPositions"""
    position = models.ForeignKey(NflPosition)

    def __unicode__(self):
        return unicode(self.position)

class College(models.Model):
    """A NCAA College"""
    name = models.TextField(max_length=30)

    def __unicode__(self):
        return self.name

class NflPlayer(models.Model):
    """Draft-eligible NFL player"""
    first_name = models.TextField()
    last_name = models.TextField()
    draft_year = models.PositiveIntegerField(default=1)
    team = models.ForeignKey(NflTeam)
    school = models.ForeignKey(College)
    position = models.ForeignKey(NflPosition)
    fantasy_position = models.ForeignKey(FantasyPosition)

    def __unicode__(self):
        return u"{f} {l}".format(f=self.first_name, l=self.last_name)


class ExternalDatabase(models.Model):
    """An external player DB ie ESPN or Yahoo"""
    name = models.TextField(max_length=20)
    description = models.TextField(max_length=200)
    homepage = models.URLField()

    def __unicode__(self):
        return self.name


class ExternalNflPlayer(models.Model):
    """Link to an external database's player info"""
    player = models.ForeignKey(NflPlayer)
    db = models.ForeignKey(ExternalDatabase)
    external_id = models.IntegerField()
    url = models.URLField()
    picture = models.URLField()


class ExternalNflTeam(models.Model):
    """Link to an external database's team info"""
    team = models.ForeignKey(NflTeam)
    db = models.ForeignKey(ExternalDatabase)
    external_id = models.IntegerField()
    url = models.URLField()


class FantasyRoster(models.Model):
    description = models.TextField() ## TODO: this should be more than a text field?
    slots = models.PositiveIntegerField()

    def __unicode__(self):
        return self.description


class FantasyDraft(models.Model):
    name = models.TextField(max_length=20)
    admin = models.EmailField()
    draft_start = models.DateTimeField()
    time_per_pick = models.PositiveIntegerField()
    team_limit = models.PositiveIntegerField()
    roster = models.ForeignKey(FantasyRoster)
    password = models.TextField(max_length=32, null=True, blank=True)

    def __unicode__(self):
        return self.name

    def picks(self):
        return FantasyPick.objects.filter(fantasy_team__draft=self)

    def is_active(self, time):
        """A draft is active if any picks are active"""
        for p in self.picks():
            if p.is_active(time):
                return True
        return False


class FantasyTeam(models.Model):
    draft = models.ForeignKey(FantasyDraft)
    name = models.TextField(max_length=80)
    email = models.EmailField()
    auth_key = models.TextField(max_length=40) # len(uuid.uuid4) == 36

    def __unicode__(self):
        return self.name

    def picks(self):
        return FantasyPick.objects.filter(fantasy_team=self)

    def remove_picks(self):
        self.picks().delete()


class FantasySeason(models.Model):
    year = models.TextField(max_length=10) # 2013-2014

    def __unicode__(self):
        return u"{} Fantasy Season".format(self.year)


class MockDraft(models.Model):
    """Ties together an existing fantasy team & a separate draft"""
    owner = models.ForeignKey(FantasyTeam)
    draft = models.ForeignKey(FantasyDraft)


class MockDraftBot(models.Model):
    season = models.ForeignKey(FantasySeason)
    draft = models.ForeignKey(FantasyDraft)
    team = models.ForeignKey(FantasyTeam)
    brain = models.TextField(max_length=12)

    def __unicode__(self):
        return u"{} bot for the {}".format(self.brain, self.season)


class FantasyPick(models.Model):
    """An upcoming pick"""
    fantasy_team = models.ForeignKey(FantasyTeam)
    starts = models.DateTimeField('starts at')
    expires = models.DateTimeField('expires at')
    pick_number = models.PositiveIntegerField()

    class Meta:
        ordering = ('pick_number',)

    def __unicode__(self):
        return u"{d} - Pick {n} - {t}" \
          .format(d=self.fantasy_team.draft.name, n=self.pick_number,
                  t=self.fantasy_team.name)

    def is_active(self, time):
        """Returns whether the time is between start & expire"""
        return self.starts <= time and \
          self.expires >= time


class FantasySelection(models.Model):
    """A pick that's been made"""
    when = models.DateTimeField(default=timezone.now())
    draft_pick = models.ForeignKey(FantasyPick)
    player = models.ForeignKey(NflPlayer)

autodraft/draftHost/views.py
import datetime

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
import django.http.response

from brake.decorators import ratelimit

from draftHost import models
from draftHost.logic import nfl, fantasy, auth, draft, json, college, site
from draftHost.logic import search as s, draft as d, mock_draft as m
from draftHost.logic.auth import AuthContext as AuthContext


def get_context_or_error(request):
    """Tries to build a AuthContext, raises an error on failure"""
    context = AuthContext(request)
    if context.is_valid():
        return context
    raise django.core.exceptions.PermissionDenied("invalid auth key")


@ratelimit(rate="30/m")
def draft_key(request):
    context = get_context_or_error(request)
    return fantasy.JsonFantasyDraft(context.draft).json_response(request)


@ratelimit(rate="30/m")
def draft_id(request, id):
    draft = get_object_or_404(models.FantasyDraft, pk=id)
    return fantasy.JsonFantasyDraft(draft).json_response(request)


def picks(request):
    context = get_context_or_error(request)
    picks = draft.PickBuilder(context.draft)
    picks.now = timezone.now()
    return picks.json_response(request)


@ratelimit(rate="20/m", field='key')
def make_pick(request, player_id):
    if request.method == "POST" or request.method == "GET":
        context = get_context_or_error(request)
        player = get_object_or_404(models.NflPlayer, pk=player_id)
        validator = draft.PickValidator(context)
        validator.draft_player(player)
        return validator.get_response(request)
    elif request.method == "OPTIONS":
        response = HttpResponse("")
        response['Access-Control-Allow-Origin'] = "*"
        response['Access-Control-Allow-Methods'] = "POST, OPTIONS"
        response['Access-Control-Allow-Headers'] = "X-Requested-With"
        response['Access-Control-Max-Age'] = "1800"
    else:
        raise django.http.response.BadHeaderError("only POST/OPTIONS allowed")


def player(request, uid):
    db_player = get_object_or_404(models.NflPlayer, pk=uid)
    json_player = nfl.JsonNflPlayer(db_player)
    return json_player.json_response(request)


def player_status(request, uid):
    db_player = get_object_or_404(models.NflPlayer, pk=uid)
    context = get_context_or_error(request)
    json_player = nfl.JsonNflPlayer(db_player)
    json_player.draft = context.draft
    json_player.show_fantasy_team = True
    return json_player.json_response(request)


def search(request, name=None, position=None):
    return s.SearchRunner() \
        .name(name) \
        .position(position) \
        .json_results() \
        .json_response(request)


def team_id(request, id):
    team = get_object_or_404(models.FantasyTeam, pk=id)
    return team_response(team, request)


def team_info_name(request, name):
    team = get_object_or_404(models.FantasyTeam, name=name)
    return team_response(team, request)


def current_team(request):
    context = get_context_or_error(request)
    return team_response(context.team, request)


def team_response(db_team, request):
    json_team = fantasy.JsonFantasyTeam(db_team)
    json_team.show_players = True
    return json_team.json_response(request)


def fantasy_team_players(request, id):
    team = get_object_or_404(models.FantasyTeam, pk=id)
    json_team = fantasy.JsonFantasyTeam(team)
    json_team.show_players = True
    return json_team.json_response(request)


def nfl_teams(request):
    teams = models.NflTeam.objects.all().exclude(name="Unknown")
    teams_json = [nfl.JsonNflTeam(t).json_dict() for t in teams]
    return json.obj_to_json({'teams': teams_json}, request)


def nfl_team(request, id):
    return nfl_team_with_players(request, id, include_players=False)


@ratelimit(rate='10/m', block=True)
def nfl_team_with_players(request, id, include_players=True):
    team = get_object_or_404(models.NflTeam, pk=id)
    json_team = nfl.JsonNflTeam(team)
    if include_players:
        json_team.show_players = True
    return json_team.json_response(request)


def nfl_divisions(request):
    divisions = models.NflDivision.objects.all()
    divisons_json = [nfl.JsonNflDivision(d).json_dict()
                     for d in divisions]
    return json.obj_to_json({'divisions': divisons_json}, request)


def nfl_conferences(request):
    conferences = models.NflConference.objects.all()
    conferences_json = [nfl.JsonNflConference(c).json_dict()
                        for c in conferences]
    return json.obj_to_json({'conferences': conferences_json}, request)


def nfl_positions(request):
    positions = models.NflPosition.objects.all()
    positions_json = [nfl.JsonNflPosition(p).json_dict()
                      for p in positions]
    return json.obj_to_json({'positions': positions_json}, request)


def colleges(request):
    colleges = models.College.objects.all().exclude(name="Unknown")
    colleges_json = []
    for c in colleges:
        colleges_json.append(college.JsonCollege(c).json_dict())
    return json.obj_to_json({'colleges': colleges_json}, request)


@ratelimit(block=True)
def college_players(request, id):
    c = get_object_or_404(models.College, pk=id)
    college_json = college.JsonCollege(c)
    college_json.show_players = True
    return college_json.json_response(request)


def my_team(request, key, write_cookie=True):
    if key == 'your-key-goes-here':
        return render(request, 'draftHost/team_hint.html', {})
    team = get_object_or_404(models.FantasyTeam, auth_key=key)
    draft = fantasy.JsonFantasyDraft(team.draft)
    context = {
        'team': team,
        'draft': draft.json_dict(),
    }
    response = render(request, 'draftHost/team_page.html', context)
    if write_cookie:
        response.set_cookie('draftKey', key)
    return response


def reg_error(request):
    return index(request, error=True)


@ratelimit(rate="20/m")
def index(request, error=False):
    now = timezone.now()
    drafts = []
    mock_drafts = models.MockDraft.objects.all()

    for d in models.FantasyDraft.objects.exclude(
            id__in=[x.draft.id for x in mock_drafts]):
        draft = fantasy.JsonFantasyDraft(d)
        draft.show_selections = False
        json = draft.json_dict()
        if d.draft_start > now + datetime.timedelta(hours=1):
            json['active'] = True

            if len(json['teams']) < d.team_limit:
                form = auth.TeamRegisterForm()
                if d.password:
                    form.add_password()
                json['registration'] = form

        drafts.append(json)
    drafts.sort(key=lambda d: d['draft_start']['utc'], reverse=True)
    context = {
        'drafts': drafts,
        'error': error,
    }
    return render(request, 'draftHost/index.html', context)


def register(request):
    if request.method == 'POST':
        form = auth.TeamRegisterForm(request.POST)
        if form.is_valid():
            creator = fantasy.FantasyTeamCreator(form.cleaned_data)
            team = creator.create_team()
            if team:
                args = {
                    'key': team.auth_key,
                }
                private_team_page = reverse('draftHost:my_team', kwargs=args)
                return HttpResponseRedirect(private_team_page)
            else:
                return HttpResponseRedirect(reverse('draftHost:error'))

        return index(request)
    else:
        raise django.http.response.BadHeaderError("only POST allowed")


def draft_detail(request, id, ajax_only=False):
    draft = get_object_or_404(models.FantasyDraft, pk=id)
    json_draft = fantasy.JsonFantasyDraft(draft).json_dict()
    now = timezone.now()
    is_active = draft.is_active(now)

    selections_queryset = models.FantasySelection.objects.filter(
        draft_pick__fantasy_team__draft=draft
    )
    selections = []
    for s in selections_queryset:
        selection_json = fantasy.JsonFantasySelection(s)
        selection_json.show_team = True
        selections.append(selection_json.json_dict())
    selections.sort(key=lambda s: s['draft_pick']['pick_number'],
                    reverse=is_active)

    picks_queryset = models.FantasyPick.objects.filter(
        fantasy_team__draft=draft
    )
    picks = []
    for p in picks_queryset:
        if now > p.expires:
            continue
        json = fantasy.JsonFantasyPick(p)
        json.now = now
        picks.append(json.json_dict())
    picks.sort(key=lambda p: p['pick_number'])
    shown_picks = len(json_draft['teams']) + 5

    context = {
        'draft': json_draft,
        'picks': picks[:shown_picks],
        'selections': selections,
        'is_active': is_active,
        'poll_time': 10000,  # 10 seconds
    }
    if ajax_only:
        return render(request, 'draftHost/detail_ajax.html', context)
    else:
        return render(request, 'draftHost/draft.html', context)


def draft_pick_ajax(request, id):
    return draft_detail(request, id, ajax_only=True)


def draft_results(request, id):
    draft = get_object_or_404(models.FantasyDraft, pk=id)
    json_draft = fantasy.JsonFantasyDraft(draft).json_dict()

    selections_queryset = models.FantasySelection.objects.filter(
        draft_pick__fantasy_team__draft=draft
    )
    selections_by_team = {}
    teams = []
    for s in selections_queryset:
        selection_json = fantasy.JsonFantasySelection(s)
        selection_json.show_team = True
        json_values = selection_json.json_dict()
        team = json_values['team']['id']
        if team not in selections_by_team:
            selections_by_team[team] = []
            teams.append(json_values['team'])
        selections_by_team[team].append(json_values)

    for t in teams:
        id = t['id']
        t['selections'] = selections_by_team.get(id, [])

    context = {
        'draft': json_draft,
        'teams': teams,
    }

autodraft/draftHost/templates/draftHost/base.html
<!DOCTYPE html>
<head>
<style type="text/css">
  .pageContent { margin:30px 0; }
  .draftList, .calls { list-style:none; }
  .draft .name { font-weight:bold; }
  .info { margin-left:50px; }
  #TWITTER { margin-top:50px; }
</style>
<title>{% block title %}Fantasy Football Drafting API{% endblock %}</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{ STATIC_URL }}bs/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="{{ STATIC_URL }}bs/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="{{ STATIC_URL }}bs/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="{{ STATIC_URL }}bs/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}bs/js/bootstrap-datetimepicker.min.js"></script>
</head>
<body>

<a href="https://github.com/gnmerritt/autodraft/" target="_"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

<div class="container-fluid pageContent">

{% block sidebar %}
<div class="span4">
  <h3>Autodraft - Fantasy Football API</h3>

  <p>Because drafting a fantasy football team by hand is lame</p>

  <h4>Links</h4>

  <ul>
    <li><a href="{% url 'draftHost:index' %}">Home</a></li>
    <li><a href="{% url 'draftHost:documentation' %}">Documentation</a></li>
    <li><a href="https://github.com/gnmerritt/autodraft" target="_">GitHub Page</a></li>
    <li><a href="https://github.com/gnmerritt/fantasy-bot">Reference bot implementation</a></li>
  </ul>

  {% if team_name %}
  <h4>Your team</h4>

  <ul>
    <li><a href="{% url 'draftHost:my_team' draftKey %}">{{ team_name }}</a></li>
    <li><a href="{% url 'draftHost:mock_draft' %}">Create a mock draft</a></li>
    {% if mock_drafts %}
      <li>Your mock drafts:
      <ul>
        {% for d in mock_drafts %}
          <li><a href="{% url 'draftHost:draft' d.draft.id %}">{{ d.draft.name }}</a></li>
        {% endfor %}
      </ul>
      </li>
    {% endif %}
  </ul>
  {% else %}
  <h4>Visit your <a href="{% url 'draftHost:my_team' 'your-key-goes-here' %}">my_team</a> page to log in & access mock drafts</h4>
  {% endif %}

  <h4>News</h4>

  <ul>
    <li>Created the 2015 drafts! Here we go again...</li>
    <li>Direct smack talk to #autodraft2015</li>
    <li>Mock drafts now available for testing after you register</li>
  </ul>
</div>
{% endblock %}

<div class="span8">
  {% block content %}{% endblock %}
</div>

</div> <!-- end container-fluid -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-43468545-2', 'gnmerritt.net');
  ga('require','displayfeatures');
  ga('send', 'pageview');
</script>
</body>
</html>

autodraft/draftHost/templates/draftHost/detail_ajax.html
<div class="pick_ajax">

{% include 'draftHost/pick_ajax.html' %}

<h3>Selections:</h3>

{% include 'draftHost/selection_ajax.html' %}

</div>

autodraft/draftHost/templates/draftHost/documentation.html
{% extends "draftHost/base.html" %}

{% block content %}

<p>By default the API will return raw JSON. JSONP can be requested by
using callback request parameter</p>

<h2>Key / Draft dependent calls:</h2>

{% include "draftHost/draft_calls.html" %}

<h2>Static calls:</h2>

{% include "draftHost/static_calls.html" %}

{% endblock %}

autodraft/draftHost/templates/draftHost/draft.html
{% extends "draftHost/base.html" %}

{% block content %}

<ul class="draftList">
  <li>{% include 'draftHost/draft_info.html' %}</li>
</ul>

{% include 'draftHost/detail_ajax.html' %}

<div id="TWITTER">
  <a class="twitter-timeline" href="https://twitter.com/hashtag/autodraft2015" data-widget-id="494962106014253056">#autodraft2015 Tweets</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

{% endblock %}

autodraft/draftHost/templates/draftHost/draft_calls.html
<p>All the following require a valid key parameter. Click on the links
for an example response.</p>

<table class="calls table table-bordered table-striped">
  <tr>
    <th>What</th>
    <th>URL pattern</th>
    <th>Returns</th>
  <tr>
  <tr>
    <td>Draft info:</td>
    <td><a href="{% url 'draftHost:api:draft' %}?key={{ key }}">{% url 'draftHost:api:draft' %}</a></td>
    <td>Draft information, teams, picks</td>
  </tr>
  <tr>
    <td>Your team:</td>
    <td><a href="{% url 'draftHost:api:current_team' %}?key={{ key }}">{% url 'draftHost:api:current_team' %}</a></td>
    <td>{ name:"Your name", picks: [list of pick objects], players: [who you've drafted] }</td>
  </tr>
  <tr>
    <td>Draft picks & selections:</td>
    <td><a href="{% url 'draftHost:api:picks' %}?key={{ key }}">{% url 'draftHost:api:picks' %}</a></td>
    <td>picks & selections</td>
  </tr>
  <tr>
    <td>Make a pick:</td>
    <td><a href="{% url 'draftHost:api:make_pick' 1623 %}?key={{ key }}">{% url 'draftHost:api:make_pick' 1623 %}</a></td>
    <td>{ code: <a href="https://github.com/gnmerritt/autodraft/blob/master/autodraft/draftHost/logic/draft.py#L145">pick status code</a>,
      success: True or missing, message: human readable state, selection: fantasy selection object }</td>
  </tr>
  <tr>
    <td>Player status in your draft:</td>
    <td><a href="{% url 'draftHost:api:player_status' 1623 %}?key={{ key }}">{% url 'draftHost:api:player_status' 1623 %}</a></td>
    <td>Returns the player object, including fantasy team if he's been
    picked. Use this if you want to check player availability before
    your turn!</td>
  </tr>

</table>

autodraft/draftHost/templates/draftHost/draft_info.html
<div class="draft">
  <div>
    <span class="name">{{ draft.name }}</span>
    <span class="admin"> - run by {{ draft.admin }}</span>
    <a href="{% url 'draftHost:api:draft_id' draft.id %}">JSON Link</a>
  </div>
  <div class="details">
    <div><a href="{% url 'draftHost:draft' draft.id %}">Detail page</a></div>
    <div><a href="{% url 'draftHost:results' draft.id %}">Draft results by team</a></div>
    <div>Roster: {{ draft.roster.description }} ({{ draft.roster.slots }} slots)</div>
    <div>
      <span>
      {% if draft.active %}
        Draft starts at
      {% else %}
        Draft started at
      {% endif %}
      {{ draft.draft_start.str }}
      </span>
      {% if draft.active %}
        <span style="font-weight: 700">
          (in {{ draft.draft_start.relative }})
        </span>
      {% endif %}
    </div>
    <div>{{ draft.time_per_pick_s }} seconds / pick</div>
  </div>
</div>

autodraft/draftHost/templates/draftHost/draft_page.html
{% extends "draftHost/base.html" %}

{% block content %}

<h1>Active Drafts</h1>

<ul class="draftList">
{% for draft in drafts %}
<li>
  {% include 'draftHost/draft_info.html' %}

  <div>Current teams ({{ draft.teams|length }} / {{ draft.team_limit }}):</div>

  <table class="teams">
    <tr>
      <th>Team</th>
      <th>Manager</th>
      <th>API Link</th>
    </tr>
    {% for team in draft.teams %}
    <tr>
      <td>{{ team.name }}</td>
      <td>{{ team.email }}</td>
      <td><a href="{% url 'draftHost:api:team_id' team.id %}">JSON Link</a></td>
    </tr>
    {% endfor %}

    {% if draft.registration %}
    <tr>
      <td>
        <span>Spots still open for this draft -- Register below:</span>
      </td>
    </tr>
    <tr>
      {% include 'draftHost/reg_form.html' %}
    </tr>
    {% endif %}
  </table>
</li>
{% endfor %}
</ul>

<h2>No drafts with open spots?</h2>

<p>TODO contact info here</p>

{% endblock %}

autodraft/draftHost/templates/draftHost/mock_draft_form.html
<form id="MOCK_DRAFT" method="POST">

  <div class="row">
    <div class="span3">
      <h3>Draft Settings</h3>
      <div id="datetimepicker2" class="input-append">
        {{ form.draft_start.label_tag }}
        <input data-format="MM/dd/yyyy HH:mm:ss PP" type="text" name="draft_start" value="{{ form.draft_start.value }}"/>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
      </div>
      {{ form.draft_start.errors }}

      {{ form.time_per_pick.label_tag }}
      {{ form.time_per_pick }}
      {{ form.time_per_pick.errors }}

      {{ form.team_limit.label_tag }}
      {{ form.team_limit }}
      {{ form.team_limit.errors }}

      {{ form.roster.label_tag }}
      {{ form.roster }}
      {{ form.roster.errors }}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% csrf_token %}
    </div>

    <div class="span3">
      <h3>Opponent AI settings</h3>
      <p>Coming soon...</p>
    </div>
  </div>

  <div class="row">
    <div class="span2 offset2">
      <button type="submit" class="btn btn-default btn-lg">Create draft</button>
    </div>
  </div>

</form>

<script type="text/javascript">
  $(function() {
    $('#datetimepicker2').datetimepicker({
      language: 'en',
      pick12HourFormat: true
    });
  });
</script>

autodraft/draftHost/templates/draftHost/reg_form.html
<form class="register" method="post" action="{% url 'draftHost:register' %}">
  {% csrf_token %}
  {{ form.non_field_errors }}

  <input type="hidden" name="draft_id" value="{{ draft.id }}"/>

  <td class="fieldWrapper">
    {{ draft.registration.name.errors }}
    <label for="name">Team name:</label>
    {{ draft.registration.name }}
  </td>

  <td class="fieldWrapper">
    {{ draft.registration.email.errors }}
    <label for="email">Email:</label>
    {{ draft.registration.email }}
  </td>

  <td>
    {% if draft.registration.has_password %}
      {{ draft.registration.password.errors }}
      <label for="password">Draft Password</label>
      {{ draft.registration.password }}
    {% endif %}
    <input type="submit" value="Register"/>
  </td>
</form>